Repository dgu-fe-master/so-mac-os, pull requests merged in 2023-05, with the labels that each got.

#13 chore: gh-pages 배포 설정
  package-lock.json
  package.json
Labels: 💙 chore

#12 feat(Calendar): 월간 캘린더 생성
  src/components/Apps/AppNexus.tsx
  src/components/Apps/Calendar/Calendar.tsx
  src/components/Apps/Calendar/View/Month/DateBox.tsx
  src/components/Apps/Calendar/View/Month/DayBox.tsx
  src/components/Apps/Calendar/View/Month/MonthView.tsx
  src/components/Apps/Calendar/View/Month/WeekBox.tsx
  src/components/Apps/Calendar/constants.ts
  src/data/apps/calendar.ts
  src/stores/calendar-store.ts
Labels: 🚀 feat

#14 feat(AboutThisMac): 이 Mac에 관하여 앱 추가
  src/assets/images/macbook.png
  src/components/Apps/AboutThisMac/AboutThisMac.tsx
  src/components/Apps/AppNexus.tsx
  src/components/Desktop/ContextMenu/ContextMenu.tsx
  src/components/Desktop/ContextMenu/MenuItem.tsx
  src/components/Dock/Dock.tsx
  src/components/Dock/DockItem.tsx
  src/components/TopBar/MenuBar/MenuBar.tsx
  src/components/TopBar/MenuBar/MenuDropDown.tsx
  src/data/apps/about-this-mac.ts
  src/data/apps/apps.ts
  src/data/utils/mac.ts
  src/hooks/useOpenApp.ts
Labels: 🚀 feat, ✏️ refactor
